name: Refresh Camo Cache

on:
  workflow_dispatch:
    inputs:
      readme_url:
        description: "GitHub URL containing markdown content and images (e.g. https://github.com/OWNER/REPO/blob/main/README.md)"
        required: false
        default: ''

jobs:
  refresh-camo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get repo info
        id: repoInfo
        run: |
          echo "REPO_PATH=${{ github.repository }}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run refreshCamo (with workflow input)
        env:
          README_URL: ${{ github.event.inputs.readme_url }}
        run: |
          URL="https://github.com/$REPO_PATH/blob/$BRANCH_NAME/README.md"
          npm run refreshCamo -- "$URL"
